### PR TITLE
Update map.geojson

### PR DESCRIPTION
**Pull request by nickyqn**

### CODE REVIEW

**Comment by nickyqn** [comment]
i think we are about done with nutsino,what do u think@MafomeB

**Comment by rustyb** [comment]
@nickyqn we need to fix up that geojson file, it would seem it's invalid.

Can you move the following lines to be within the `properties` section:

``` json
{
  "name": "Foso",
  "area": "1190.9",
  "centre_point": "=[-29.2842,27.5630]",
  "perimeter": "26451.02",
  "team": "Lioli_Analysis_Team"
}
```

to be something like this:

``` json
{
      "type": "Feature",
      "properties": {
        "stroke": "#555555",
        "stroke-width": 2,
        "stroke-opacity": 1,
        "fill": "#555555",
        "fill-opacity": 0.5,
  "name": "Foso",
  "area": "1190.9",
  "centre_point": "=[-29.2842,27.5630]",
  "perimeter": "26451.02",
  "team": "Lioli_Analysis_Team"
      },........
```

**Comment by nickyqn** [comment]
OK

**Comment by rustyb** [comment]
You're almost there look at the file at https://github.com/nickyqn/lioli-analysis-team/blob/patch-2/map.geojson?short_path=bebff5e

You've got two too many { } curley braces!

``` json
{
      "type": "Feature",
      "properties": {
        "stroke": "#555555",
        "stroke-width": 2,
        "stroke-opacity": 1,
        "fill": "#555555",
        "fill-opacity": 0.5,
{ // remove this line completely
  "name": "Foso",
  "area": "1190.9",
  "centre_point": "=[-29.2842,27.5630]",
  "perimeter": "26451.02",
  "team": "Lioli_Analysis_Team"
 } // remove this line completely
        "test": "test"
      },

```

Then you're good

**Comment by Nuts2001** [comment]
https://github.com/Nuts2001/lioli-analysis-team/blob/patch-2/map.geojson @rustyb how's this now?

**Pull request closed without merging**
